services:
  postgres:
    image: postgres:16
    container_name: IDA-WorkTogether-PG
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  python:
    build:
      context: ./app
    container_name: IDA-WorkTogether-PY
    working_dir: /app
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    ports:
      - "19999:9999"
    command: python server.py

volumes:
  pgdata:
